platzigram/urls.py
"""Platzigram URLs module"""

#Djangoo
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

#Graphql
from graphene_django.views import GraphQLView


#Views
#from platzigram import views as local_views

#URLs


urlpatterns = [

    path('admin/', admin.site.urls),
    url(r'^graphql$', GraphQLView.as_view(graphiql=True)),

    # path('hello-world', local_views.hello_world, name='hello_world'),
    # path('sorted/', local_views.sort_int, name='sort'),
    # path('hi/<str:name>/>int:age>/', local_views.say_hi, name='hi'),

    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('users/', include(('users.urls', 'users'), namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
"""Posts URLS"""

#Django
from django.urls import path

#Views
from posts import views

#cache
from django.core.cache import cache
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)


urlpatterns = [
    
    path(
        route='', 
        view=cache_page(CACHE_TTL)(views.PostsFeedView.as_view()), #high order component
        name='feed'
    ),

    path(
        route='posts/new/', 
        view=views.CreatePostView.as_view(), 
        name='create'
    ),

    path(
        route='posts/<int:pk>',
        view=views.PostDetailView.as_view(),
        name='detail'
    )
    
]

users/urls.py
"""Users URLs"""

#Django
from django.urls import path, include
from rest_framework import routers


#Views
from users import views


#cache
from django.core.cache import cache
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

router = routers.DefaultRouter()
router.register(r'listUser', views.UserViewSet) # r de recursive para generar las vistas de los usuarios
router.register(r'profiles', views.ProfileViewSet)

urlpatterns = [
    
    # Management
    path(
        route='login/', 
        view=cache_page(60 * 15)(views.LoginView.as_view()), 
        name='login'
    ),
    
    path(
        route='logout/', 
        view=views.LogoutView.as_view(), 
        name='logout'
    ),
    
    path(
        route='signup/', 
        view=views.SignupView.as_view(), 
        name='signup'
    ),

    path(
        route='me/profile/', 
        view=views.UpdateProfileView.as_view(), 
        name='update'
    ),

    #Posts
    path(
        route='detail/<str:username>/',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    #RestViews
    path(
        route='',
        view=include(router.urls),
        name='api'
    ),
    path('api-auth', include('rest_framework.urls', namespace='rest_framework')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head_content %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                {# agrergar el tamaño de la barra tamaños a mostrar#}
                <li class="nav-item"> 
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="50" width="50" 
                            class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png'%}" height="50" width="50"
                            class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>